'************************************************************************
' STARWARS.BAS - Die Starwars Melodie in QBasic
' ================================================
'************************************************************************
PLAY "t136 mn o3 l8" 
PLAY "ddgfe-dc o2 b-ag o3 d2. l12 ddd l8 g4 p4 p2 p2 " 
PLAY "t236 l6 o2 ddd l2 ml g o3 dd mn l6 c o2 ba l2 o3 ml gdd" 
PLAY "mn l6 c o2 ba ml l2 o3 gdd mn l6 c o2 b o3 c l2 ml o2 a1a4 p4 mn" 
PLAY "t236 l6 o2 ddd l2 ml g o3 dd mn l6 c o2 ba l2 o3 ml gdd" 
PLAY "mn l6 c o2 ba ml l2 o3 gdd mn l6 c o2 b o3 c l2 ml o2 a1a4 p4 mn" 
PLAY "t136 mn o3 l8" 
PLAY "p4 mn o2 l8 d4 e4.e o3c o2 bag l12 gab l8 a8. e16f+4d8. d" 
PLAY "e4.e o3 c o2 bag o3 d8.o2   a16 ml a4a4 mn d4 e4.e O3 c o2 bag " 
PLAY "l12 gaba8. e16 f+4 o3 d8. d16 l16   g8. fe-8. d c8. o2 b-a8. g" 
PLAY "o3 d2" 
PLAY "t236 l6 o2 ddd l2 ml g o3 dd mn l6 c o2 ba l2 o3 ml gdd" 
PLAY "mn l6 c o2 ba ml l2 o3 gdd mn l6 co2 b o3c l2 ml o2a1a4 p4 mn" 
PLAY "t236 l6 o2 ddd l2 ml g o3 dd mn l6 c o2 ba l2 o3 ml gdd" 
PLAY "mn l6 c o2ba ml l2 o3gdd mn l6 co2bo3c l2 ml o2a1a4 p4 mn" 
PLAY "l6 o3 mn ddd ml l1 gggg4 p4 p4 mn l12 dddg2" 
