$SCREENHIDE
$CONSOLE
_DEST _CONSOLE

COLOR 15
PRINT "Copy this text by highlighting and right clicking!" 
COLOR 14
PRINT "Copy this text by highlighting and right clicking!" 
COLOR 13
PRINT "Copy this text by highlighting and right clicking!" 
COLOR 12
PRINT "Copy this text by highlighting and right clicking!" 
COLOR 11
PRINT "Copy this text by highlighting and right clicking!" 
COLOR 10
PRINT "Copy this text by highlighting and right clicking!" 
COLOR 9
PRINT "Copy this text by highlighting and right clicking!" 
COLOR 8
PRINT "Copy this text by highlighting and right clicking!" 
