''
' GRYMMJACK'S LIB FOR QB64
'
' This is the master BI file, which includes the other BI files for the library.
'
' @author Rick Christy <grymmjack@gmail.com>
' @uses DICT.BI
' @uses DUMP.BI
' @uses ANSI.BI
' @uses STRINGS.BI
'
CONST FALSE = 0: CONST TRUE = NOT FALSE
CONST _GJ_LIB_INC = TRUE
CONST _GJ_LIB_DEBUGGING = TRUE

'$INCLUDE:'DICT.BI'
'$INCLUDE:'DUMP.BI'
'$INCLUDE:'ANSI.BI'
'$INCLUDE:'STRINGS.BI'